# Generated by Django 4.0.4 on 2022-05-27 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=64, verbose_name='категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_name', models.CharField(max_length=100)),
                ('gas_type', models.CharField(default='', max_length=50)),
                ('gas_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
            ],
            options={
                'verbose_name': 'Паливо',
                'verbose_name_plural': 'Паливо',
                'ordering': ('gas_price', 'gas_type'),
            },
        ),
        migrations.CreateModel(
            name='PastStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=700)),
                ('start_stock', models.DateField()),
                ('end_stock', models.DateField()),
            ],
            options={
                'verbose_name': 'Минула акція',
                'verbose_name_plural': 'Минулі акції',
                'ordering': ('short_text', 'start_stock'),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=700)),
                ('start_stock', models.DateField()),
                ('end_stock', models.DateField()),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
                'ordering': ('short_text', 'start_stock'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='назва')),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(default='One', on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ('name', 'category'),
            },
        ),
    ]
