# Generated by Django 4.0.4 on 2022-05-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(default='-', max_length=300, verbose_name='довга назва'),
        ),
    ]
