# Generated by Django 4.0.4 on 2022-05-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='-', max_length=600, verbose_name='Характерстика'),
        ),
    ]
