# Generated by Django 4.0.4 on 2022-05-29 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 23, 20, 17, 605319), verbose_name='Створений'),
        ),
    ]
