# Generated by Django 4.0.4 on 2022-05-29 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cart_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошик'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 23, 21, 56, 82276), verbose_name='Створений'),
        ),
    ]
