# Generated by Django 4.0.4 on 2022-06-01 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cart_created_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 14, 37, 20, 94546), verbose_name='Створений'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
