# Generated by Django 4.0.4 on 2022-06-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_orderproduct_item_remove_orderproduct_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='-', max_length=300, verbose_name='довга назadwва')),
                ('name', models.CharField(max_length=200, verbose_name='назawdва')),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(default='-', verbose_name='Характwwерстика')),
                ('category', models.ForeignKey(default='One', on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='предDAмет')),
            ],
            options={
                'verbose_name': 'Преwwдмет',
                'verbose_name_plural': 'Предwwмети',
                'ordering': ('name', 'category'),
            },
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
