# Generated by Django 4.0.4 on 2022-06-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cheese_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheese',
        ),
    ]
