# Generated by Django 4.0.4 on 2022-06-02 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_cheese'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('full_text', models.TextField(verbose_name='Повідомлення')),
                ('number', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 23, 39, 6, 597070), verbose_name='Додано')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ('first_name', 'created'),
            },
        ),
    ]
