# Generated by Django 4.0.4 on 2022-06-04 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_comment_created_alter_service_created_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('user', 'name'), 'verbose_name': 'Коментарій', 'verbose_name_plural': 'Коментарії'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 4, 20, 56, 37, 534466), null=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 20, 56, 37, 533468), verbose_name='Додано'),
        ),
    ]
