# Generated by Django 4.0.4 on 2022-06-04 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_order_options_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 4, 21, 1, 31, 479117), null=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 1, 31, 479117, tzinfo=utc), verbose_name='Додано'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 21, 1, 31, 478117), verbose_name='Додано'),
        ),
    ]
