# Generated by Django 4.0.4 on 2022-06-09 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_service_services_alter_comment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 9, 13, 7, 57, 67464), null=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 13, 7, 57, 66464), verbose_name='Додано'),
        ),
        migrations.AlterField(
            model_name='service',
            name='services',
            field=models.CharField(blank=True, choices=[('Ремонт лічильників рідини', 'Ремонт лічильників рідини'), ('Ремонт паливних колонок', 'Ремонт паливних колонок'), ('Обслуговування паливних резервуарів', 'Обслуговування паливних резервуарів')], max_length=100, null=True),
        ),
    ]
