# Generated by Django 4.0.4 on 2022-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Зображення'),
        ),
    ]
